WeChatSwitch/WebChatSwitch.Web/Models/ItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WeChatSwitch.Web.Models
{
    public class ItemViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Expectation")]
        public string Expectation { get; set; }

        [Display(Name = "Available")]
        public bool Available { get; set; }

        [Display(Name = "Photos")]
        public List<string> ItemPhotos { get; set; }

        [Display(Name = "PublishUser")]
        public string PublishUser { get; set; }

        [Display(Name = "PublishUserOpenId")]
        public string PublishUserOpenId { get; set; }
    }
}

WeChatSwitch/WebChatSwitch.Web/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WeChatSwitch.BLL;
using WeChatSwitch.DAL;
using WeChatSwitch.Web.Models;
using WeChatPublicAccount;

namespace WeChatSwitch.Web.Controllers
{
    public class ItemController : WeChatBaseController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
        }

        // GET: Item
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            string url = Request.Url.ToString();
            //判断是否有OpenId
            if (CurrentUser == null || string.IsNullOrWhiteSpace(CurrentUser.OpenId))
            {
                LogManager logManager = new LogManager();
                SystemLog log = new SystemLog()
                {
                    Type = "Error",
                    Content = string.Format("Failed to get OpenId, requested url:{0}", url),
                    Time = DateTime.UtcNow
                };
                logManager.AddLog(log);
            }

            ItemViewModel vm = new ItemViewModel();
            vm.Available = true;
            vm.ItemPhotos = new List<string>();
            vm.ItemPhotos.Add(string.Empty);
            vm.ItemPhotos.Add(string.Empty);
            vm.ItemPhotos.Add(string.Empty);

            JsInitResponse response = InitialWechatSDK(url);
            ViewBag.appId = response.appId;
            ViewBag.nonceStr = response.nonceStr;
            ViewBag.signature = response.signature;
            ViewBag.timestamp = response.timestamp;

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(string Title, string Description, string Expectation, string Available, string[] ServerIds)
        {
            LogManager logManager = new LogManager();
            SystemLog log = new SystemLog()
            {
                Type = "Log",
                Content = string.Format("Item Create Action post called.Title:{0}, Description{1}, Expectation{2}, Available:{3}, ServerId1:{4}",
                    Title, Description, Expectation, Available, ServerIds == null ? "null" : ServerIds[0]),
                Time = DateTime.UtcNow
            };
            logManager.AddLog(log);

            bool result;
            if (bool.TryParse(Available, out result))
            {
                Item item = new Item()
                {
                    Title = Title,
                    Description = Description,
                    Expectation = Expectation,
                    Available = result,
                    PublishedTime = DateTime.Now
                };

                if (CurrentUser != null)
                {
                    item.OwnerId = CurrentUser.Id;
                }

                foreach (var serverId in ServerIds)
                {
                    string fileName = WeChatDownloadImage(serverId);
                    string rootPath = ConfigurationManager.AppSettings["Domain"];
                    string ftpUrl = rootPath + "/" + ConfigurationManager.AppSettings["photoFolder"] + "/" + fileName;
                    string ftpUrlForResized = rootPath + "/" + ConfigurationManager.AppSettings["resizedPhotoFolder"] + "/" + fileName;
                    if (!string.IsNullOrEmpty(ftpUrl))
                    {
                        SystemLog downlog = new SystemLog()
                        {
                            Type = "Log",
                            Content = "Saved image to " + ftpUrl,
                            Time = DateTime.UtcNow
                        };
                        logManager.AddLog(downlog);
                    }

                    ItemPicture pic = new ItemPicture()
                    {
                        PictureUrl = ftpUrl
                    };
                    item.ItemPictures.Add(pic);
                }

                ItemManager manager = new ItemManager();
                if (manager.SaveNewItem(item))
                {
                    return Content("true");
                }
                else
                {
                    SystemLog dblog = new SystemLog()
                    {
                        Type = "Log",
                        Content = "Failed to save Item to DB.",
                        Time = DateTime.UtcNow
                    };
                    logManager.AddLog(dblog);
                    return Content("false");
                }
            }
            else
            {
                SystemLog parseFailLog = new SystemLog()
                {
                    Type = "Log",
                    Content = "Failed to parse Available.",
                    Time = DateTime.UtcNow
                };
                logManager.AddLog(parseFailLog);
                return Content("false");
            }
        }

        public ActionResult ListView(string searchString)
        {
            string url = Request.Url.ToString();
            //判断是否有OpenId
            if (CurrentUser == null || string.IsNullOrWhiteSpace(CurrentUser.OpenId))
            {
                LogManager logManager = new LogManager();
                SystemLog log = new SystemLog()
                {
                    Type = "Error",
                    Content = string.Format("Failed to get OpenId, requested url:{0}", url),
                    Time = DateTime.UtcNow
                };
                logManager.AddLog(log);
            }

            JsInitResponse response = InitialWechatSDK(url);
            ViewBag.appId = response.appId;
            ViewBag.nonceStr = response.nonceStr;
            ViewBag.signature = response.signature;
            ViewBag.timestamp = response.timestamp;

            ItemManager manager = new ItemManager();
            List<ItemViewModel> itemList = new List<ItemViewModel>();
            List<Item> items;
            if (!string.IsNullOrEmpty(searchString))
            {
                items = manager.GetAvailableItems(searchString);
            }
            else
            {
                items = manager.GetAllAvailableItems();
            }
            foreach (var item in items)
            {
                ItemViewModel vm = new ItemViewModel();
                vm.Available = item.Available;
                List<string> photoes = new List<string>();
                foreach (ItemPicture ip in item.ItemPictures)
                {
                    photoes.Add(ip.PictureUrl);
                }
                vm.ItemPhotos = photoes;
                vm.PublishUser = item.UserAccount.Name;
                vm.PublishUserOpenId = item.UserAccount.OpenId;
                vm.Title = item.Title;
                vm.Description = item.Description;
                vm.Expectation = string.IsNullOrEmpty(item.Expectation) ? null : " | " + item.Expectation;
                itemList.Add(vm);
            }

            return View(itemList);
        }
    }
}

WeChatSwitch/WebChatSwitch.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WeChatSwitch.BLL;
using WeChatSwitch.DAL;
using WeChatSwitch.Web.Models;
using WeChatPublicAccount;

namespace WeChatSwitch.Web.Controllers
{
    public class UserController : WeChatBaseController
    {
        #region ViewUserInfo
        public ActionResult ViewUserInfo()
        {
            string url = Request.Url.ToString();
            JsInitResponse response = InitialWechatSDK(url);
            ViewBag.appId = response.appId;
            ViewBag.nonceStr = response.nonceStr;
            ViewBag.signature = response.signature;
            ViewBag.timestamp = response.timestamp;
            string queryOpenId = Request.QueryString["openid"];

            //todo get date form database
            UserAccountManager manager = new UserAccountManager();

            if (string.IsNullOrWhiteSpace(queryOpenId))
            {
                queryOpenId = CurrentUser.OpenId;
            }

            UserAccount userInfo = manager.GetUserAccountInfoByOpenId(queryOpenId);
            userInfo.WeChatNumber = userInfo.WeChatNumber;
            userInfo.OpenId = CurrentUser.OpenId;               //get open id
            userInfo.Name = userInfo.Name;
            userInfo.WeChatNickName = userInfo.WeChatNickName;
            userInfo.Remark = userInfo.Remark;
            userInfo.Balance = userInfo.Balance;

            return View(userInfo);
        }
        #endregion

        #region ViewMyItem
        public ActionResult ViewMyItem()
        {
            string url = Request.Url.ToString();
            JsInitResponse response = InitialWechatSDK(url);
            ViewBag.appId = response.appId;
            ViewBag.nonceStr = response.nonceStr;
            ViewBag.signature = response.signature;
            ViewBag.timestamp = response.timestamp;
            string code = Request.Params["code"];
            //判断是否有OpenId
            if (CurrentUser == null || string.IsNullOrWhiteSpace(CurrentUser.OpenId))
            {
                LogManager logManager = new LogManager();
                SystemLog log = new SystemLog()
                {
                    Type = "Error",
                    Content = string.Format("Failed to get OpenId, requested url:{0}", url),
                    Time = DateTime.UtcNow
                };
                logManager.AddLog(log);
            }
            return View();
        }

        public ActionResult GetMyItem()
        {
            List<ItemViewModel> itemList = new List<ItemViewModel>();

            try
            {
                ItemManager manager = new ItemManager();

                List<Item> items;
                LogManager logManager = new LogManager();
                //SystemLog log = new SystemLog();
                //log.Type = "Log";
                //log.Content = $"[View My Item] User Id: { CurrentUser.Id}; Oped Id: { CurrentUser.OpenId}";
                //log.Time = DateTime.UtcNow;
                //logManager.AddLog(log);
                items = manager.GetMyItems(CurrentUser.Id);
                foreach (var item in items)
                {
                    ItemViewModel vm = new ItemViewModel();
                    vm.Id = item.Id;
                    vm.Available = item.Available;
                    List<string> photoes = new List<string>();
                    foreach (ItemPicture ip in item.ItemPictures)
                    {
                        photoes.Add(ip.PictureUrl);
                    }
                    vm.ItemPhotos = photoes;
                    vm.PublishUser = item.UserAccount.Name;
                    vm.Title = item.Title;
                    vm.Description = item.Description;
                    vm.Expectation = item.Expectation;
                    itemList.Add(vm);
                }
            }
            catch (Exception ex)
            {
                LogManager logManager = new LogManager();
                SystemLog log = new SystemLog();
                log.Type = "Log";
                log.Content = $"[View My Item] Page Error: { ex.Message }";
                log.Time = DateTime.UtcNow;
                logManager.AddLog(log);
            }

            return Json(itemList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SoldOut()
        {
            string id = Request.Form["id"];

            int intId;

            if (!int.TryParse(id, out intId))
            {
                return Json("Id not number");
            }

            ItemManager manager = new ItemManager();
            manager.SoldOut(intId);

            return Json("Succeed");
        }
        #endregion

        #region ViewEditMyInfo

        public ActionResult ViewEditMyInfo()
        {
            string url = Request.Url.ToString();
            JsInitResponse response = InitialWechatSDK(url);
            ViewBag.appId = response.appId;
            ViewBag.nonceStr = response.nonceStr;
            ViewBag.signature = response.signature;
            ViewBag.timestamp = response.timestamp;
            return View();
        }

        public ActionResult GetMyInfo()
        {
            UserAccount userInfo = new UserAccount();
            UserAccountManager manager = new UserAccountManager();
            userInfo = manager.GetUserAccountInfoByOpenId(CurrentUser.OpenId);
            return Json(userInfo, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveMyInfo()
        {
            string opedId = Request.Form["OpenId"];
            string weChatAccount = Request.Form["WeChatAccount"];
            string name = Request.Form["Name"];
            string remark = Request.Form["SelfIntroduction"];

            UserAccount userInfo = new UserAccount();
            if (!string.IsNullOrWhiteSpace(opedId))
            {
                userInfo.OpenId = opedId;
                userInfo.WeChatNumber = weChatAccount;
                userInfo.Name = name;
                userInfo.Remark = remark;

                UserAccountManager manager = new UserAccountManager();
                manager.SaveUserAccountInfo(userInfo);
            }

            return Json("Save succeed!");
        }
        #endregion
    }
}

WeChatSwitch/WebChatSwitch.Web/Views/Item/Create.cshtml
@model WebChatSwitch.Web.Models.ItemViewModel

@{
    ViewBag.Title = "Publish";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="controlForm">
        @*<div class="controlBlock">
                <div class="controlLabel">
                    <h2>Publish Item</h2>
                </div>
            </div>*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="controlBlock">
            <div class="controlLabel">
                <p>
                    Title:
                </p>
            </div>
            <div class="controlContent">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="controlBlock">
            <div class="controlLabel">
                <p>
                    Description:
                </p>
            </div>
            <div class="controlContent">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="controlBlock">
            <div class="controlLabel">
                <p>
                    Expectation:
                </p>
            </div>
            <div class="controlContent">
                @Html.EditorFor(model => model.Expectation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expectation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="controlBlock">
            <div class="controlLabel">
                <p>
                    Available:
                </p>
            </div>
            <div class="controlContent">
                <div>
                    <div>
                        @Html.RadioButtonFor(model => model.Available, true)
                    </div>
                    <div>
                        <p>Yes</p>
                    </div>
                </div>
                <div>
                    <div>
                        @Html.RadioButtonFor(model => model.Available, false)
                    </div>
                    <div>
                        <p>No</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="controlBlock">
            <div class="controlLabel">
                <p>
                    Photos:
                </p>
            </div>
            <div class="controlContent">
                <div class="demo-wrap upload-demo am-center" style="display:none;">
                    <div class="upload-msg">
                        Upload a file to start cropping
                    </div>
                    <div id="upload-demo"></div>
                </div>
                <input type="hidden" name="Photo1" />
                <input type="hidden" name="Photo2" />
                <input type="hidden" name="Photo3" />
                <input type="button" id="chooseBtn" onclick="chooseImage()" value="ChoosePhoto" />
                <div id="img" class="imageList"><p>Don't have upload any Photo</p></div>
            </div>
        </div>

        <div class="controlBlock">
            <div class="controlContent">
                <input type="submit" value="Create" />
            </div>
        </div>

        <div class="controlBlock">
            <label id="info" name="info" class="alert alert-info" style="display:none"></label>
        </div>
    </div>
}

<script src="~/Scripts/croppie.min.js"></script>
<link href="~/Content/croppie.css" rel="stylesheet" />
<script type="text/javascript">
    var images = {
        localIds: [],
        serverIds: []
    };

    function chooseImage() {
        images = {
            localIds: [],
            serverIds: []
        };

        wx.chooseImage({
            count: 3, // 默认9
            sizeType: ['compressed'], // 可以指定是原图还是压缩图，默认二者都有
            sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
            success: function (res) {
                images.localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
                var i = 0;
                var length = images.localIds.length;
                $("#img").empty();
                var upload = function () {
                    //alert("uploading photo, localId: " + images.localIds[i].toString());
                    wx.uploadImage({
                        localId: images.localIds[i],
                        success: function (res) {

                            var serverId = res.serverId; // 返回图片的服务器端ID
                            //alert("uploaded photo, serverId: " + res.serverId);
                            images.serverIds.push(res.serverId);
                            $("#img").append('<img src="' + res.localId + '"  />');
                            //alert('<img src="' + res.localId + '" />');
                            //downloadImage(res.serverId);

                            //如果还有照片，继续上传
                            i++;
                            if (i < length) {
                                //alert("continue uploading");
                                upload();
                            }
                        },
                        fail: function (res) {
                            alert(JSON.stringify(res));
                        }
                    });
                };

                upload();

                //jQuery(function () {
                //    $.each(images.serverIds, function (i, n) {
                //        alert("serverId " + i + ":" + images.serverIds[i]);
                //    });
                //});
            }
        });
    }

    $(function () {
        $('form').submit(function () {
            if ($(this).valid()) {
                var btn = $('button:submit');
                btn.attr('disabled', true);

                var Title = $("[name='Title']").val();
                var Description = $("[name='Description']").val();
                var Expectation = $("[name='Expectation']").val();
                var Available = $("[name='Available']:checked").val();

                $.ajax({
                    url: "Create",
                    method: 'POST',
                    data: { Title: Title, Description: Description, Expectation: Expectation, Available: Available, ServerIds: images.serverIds },
                    success: function (data) {
                        if (data == 'true') {
                            //$("[name='info']").text("Successfully published");
                            window.location = "https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx25c7164abf77f19c&redirect_uri=@System.Configuration.ConfigurationManager.AppSettings["Domain"]/User/ViewMyItem&response_type=code&scope=snsapi_base&state=create#wechat_redirect";
                        }
                        else {
                            $("[name='info']").text("Failed to publish");
                        }
                    },
                    error: function () {
                        $("[name='info']").text("Error");
                    },
                    complete: function () {
                        $("[name='info']").css("display", "inline");
                    }
                });
            }
            return false;
        });
    })
</script>

WeChatSwitch/WebChatSwitch.Web/Views/Item/ListView.cshtml
@model List<WebChatSwitch.Web.Models.ItemViewModel>

@{
    ViewBag.Title = "Item List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="controlForm controlForm-Gray">
    <div class="searchArea">
        @using (Html.BeginForm("ListView", "Item", FormMethod.Get))
            {   <div class="searchText">
            @Html.TextBox("searchString", "", new { htmlAttributes = new { @class = "txtSearch" } })
        </div>
        <div class="searchButton">
            <input type="submit" value="" class="submitSearch" />
        </div>
        }
    </div>

    <div class="searchResult">
        @{
            if (Model.Count() == 0)
            {
                <div class="item">
                    <p>
                        No Items
                    </p>
                </div>
            }
            else
            {
                foreach (var item in Model)
                {
                    <div class="item">
                        <div class="itemTitle">
                            @Html.DisplayFor(modelItem => item.Title)
                        </div>
                        <div class="itemAuthor">
                            @Html.ActionLink(item.PublishUser, "ViewUserInfo", "User", new { openid = item.PublishUserOpenId }, new { display = "in-lilne" })
                        </div>
                        <div class="imageList">
                            @foreach (var pic in item.ItemPhotos)
                            {
                                <img src='@pic' style="height:90px;" />
                            }
                        </div>
                        <div class="itemDescript">
                            @Html.DisplayFor(modelItem => item.Description)  @Html.DisplayFor(modelItem => item.Expectation)
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>

<script>
    $(function () {
        $("img").click(function () {
            var imgArray = [];
            var curImageSrc = $(this).attr('src');
            var oParent = $(this).parent();
            if (curImageSrc && !oParent.attr('href')) {
                oParent.find('img').each(function (index, el) {
                    var itemSrc = $(this).attr('src');
                    imgArray.push(itemSrc);
                });
                wx.previewImage({
                    current: curImageSrc,
                    urls: imgArray
                });
            }
        });
    })
</script>